Models/ErrorViewModel.cs
namespace CascadeBrewingCo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Product.cs
using System;
using Newtonsoft.Json;

namespace CascadeBrewingCo.Models
{
    // C# record representing an item in the container
    public record Product(
        string id,
        string categoryId,
        string categoryName,
        string name,
        int quantity,
        bool sale
    );
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CascadeBrewingCo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Azure.Cosmos;
using Microsoft.VisualBasic;
using System.Data;
using System.Net;

namespace CascadeBrewingCo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly CosmosClient _cosmosClient;
    private readonly IConfiguration _configuration;

    public HomeController(ILogger<HomeController> logger, CosmosClient cosmosClient, IConfiguration configuration)
    {
        _logger = logger;
        _cosmosClient = cosmosClient;
        _configuration = configuration;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Controllers/ImageController.cs
using System;
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.Options;
using System.Threading;

namespace CascadeBrewingCo.Controllers
{
    public class ImageController : Controller
    {
        private readonly ILogger<InventoryController> _logger;
        private readonly CosmosClient _cosmosClient;
        private readonly BlobContainerClient _containerClient;
        private readonly IConfiguration _configuration;

        public ImageController(ILogger<InventoryController> logger, CosmosClient cosmosClient, BlobContainerClient containerClient, IConfiguration configuration)
        {
            _logger = logger;
            _cosmosClient = cosmosClient;
            _containerClient = containerClient;
            _configuration = configuration;
        }


        public async Task<ActionResult> GetBlob()
        {
            //Create a unique name for the container
          
            await _containerClient.CreateIfNotExistsAsync(PublicAccessType.Blob);

            // Retreive blobs
            List<Uri> allBlobs = new List<Uri>();
            foreach (BlobItem blob in _containerClient.GetBlobs())
            {
                Console.WriteLine(blob.Name);
                if (blob.Properties.BlobType == BlobType.Block)
                    allBlobs.Add(_containerClient.GetBlobClient(blob.Name).Uri);
            }

            
            return View(allBlobs);

        }
        
    }
}

Controllers/InventoryController.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CascadeBrewingCo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.Logging;
using Microsoft.VisualBasic;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using System.Net.Http;
using Azure;
using Azure.Storage.Blobs;

namespace CascadeBrewingCo.Controllers
{
	public class InventoryController : Controller
	{
        private readonly ILogger<InventoryController> _logger;
        private readonly CosmosClient _cosmosClient;


        public InventoryController(ILogger<InventoryController> logger, CosmosClient cosmosClient)
		{
            _logger = logger;
            _cosmosClient = cosmosClient;
        }

        public async Task AddInventory()
        {
            var container = _cosmosClient.GetContainer("CascadeBrewsDb", "brews");
            // Create new object and upsert (create or replace) to container
            Product newItem = new(
                id: "70b63682-b93a-4c77-aad2-65501347284f",
                categoryId: "61dba35b-4f02-45c5-b648-c6badc0cbd79",
                categoryName: "Beer",
                name: "Blue Bird Pale Ale",
                quantity: 12,
                sale: false
            );

            Product createdItem = await container.CreateItemAsync<Product>(newItem);

            Console.WriteLine($"Created item:\t{createdItem.id}\t[{createdItem.categoryName}]");
        }

        [HttpGet]
        public async Task<IActionResult> GetInventory()
        {
            var container = _cosmosClient.GetContainer("CascadeBrewsDb", "brews");
            try
            {
                // Create query using a SQL string and parameters
                var query = new QueryDefinition(
                    query: "SELECT * FROM c"
                );

                using FeedIterator<Product> feed = container.GetItemQueryIterator<Product>(
                    queryDefinition: query
                );
                List<Product> products = new List<Product>();
                while (feed.HasMoreResults)
                {
                    FeedResponse<Product> response = await feed.ReadNextAsync();
                    foreach (Product item in response)
                    {
                        products.Add(item);
                        Console.WriteLine($"Found item:\t{item.name}");
                    }
                }
                
                return View(products);
            }
            catch
            {
                throw new Exception($"No Brews Today");
            }

        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Cascade Brewing Co</h1>
</div>

Views/Home/OnTap.cshtml
@model CascadeBrewingCo.Models.Product

@{
    ViewData["Title"] = "Brews On Tap";
}
<h1>@ViewData["Title"]</h1>

<p>@Model.name</p>

Views/Image/GetBlob.cshtml
@model List<Uri>

@{
    ViewData["Title"] = "Images";
}

@if (Model != null && Model.Count > 0)
{
    foreach (var item in Model)
    {
        <div class="imageBlock">
            <a href="@item" target="_blank"><img class="thumb" src="@item" alt="images" /></a>
        </div>
    }
}

Views/Inventory/GetInventory.cshtml
@model List<CascadeBrewingCo.Models.Product>

@{
    ViewData["Title"] = "Brews On Tap";
}
<h1>@ViewData["Title"]</h1>


@foreach (var item in Model)
{
    <li>@item.name</li>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CascadeBrewingCo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CascadeBrewingCo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CascadeBrewingCo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="GetInventory">On Tap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="GetBlob">Photos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CascadeBrewingCo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>